package com.vamshi.field.ui.theme

import androidx.compose.ui.graphics.Color

// AUTO-GENERATED from design.md - DO NOT EDIT MANUALLY

val ElectricBlue = Color(0xFF0052FF)
val DynamicOrange = Color(0xFFFF5E00)
val AquaCyan = Color(0xFF00D1FF)
val NavyVariant = Color(0xFF1B263B)
val NavyPrimary = Color(0xFF0052FF)
val SportBlue = Color(0xFF0052FF)
val VibrantBlue = Color(0xFF0052FF)
val BlueAccent = Color(0xFF00D1FF)
val SportOrange = Color(0xFFFF5E00)
val SportOrangeVariant = Color(0xFFE65100)
val SportOrangeContainer = Color(0xFFFFF4EC)
val PeachIconBg = Color(0xFFF6D0C0)
val BlueIconBg = Color(0xFFC7D7FF)
val SurfaceWhite = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF7F9FA)
val TextPrimary = Color(0xFF111827)
val TextSecondary = Color(0xFF6B7280)
val OutlineGrey = Color(0xFFE5E7EB)
val PerformanceGreen = Color(0xFFE8F5E9)
val PerformanceGreenText = Color(0xFF1B5E20)
val PerformanceGreenBorder = Color(0xFFA5D6A7)
val PerformanceYellow = Color(0xFFFFFDE7)
val PerformanceYellowText = Color(0xFFF57F17)
val PerformanceYellowBorder = Color(0xFFFFF59D)
val PerformanceRed = Color(0xFFFFEBEE)
val PerformanceRedText = Color(0xFFB71C1C)
val PerformanceRedBorder = Color(0xFFEF9A9A)
val PerformanceGrey = Color(0xFFFAFAFA)
val PerformanceGreyText = Color(0xFF757575)
val PerformanceGreyBorder = Color(0xFFEEEEEE)
val PerformanceGreenDark = Color(0xFF14532D)
val PerformanceGreenTextDark = Color(0xFF86EFAC)
val PerformanceGreenBorderDark = Color(0xFF166534)
val PerformanceYellowDark = Color(0xFF713F12)
val PerformanceYellowTextDark = Color(0xFFFDE047)
val PerformanceYellowBorderDark = Color(0xFF854D0E)
val PerformanceRedDark = Color(0xFF7F1D1D)
val PerformanceRedTextDark = Color(0xFFFDA4AF)
val PerformanceRedBorderDark = Color(0xFF991B1B)
val PerformanceGreyDark = Color(0xFF374151)
val PerformanceGreyTextDark = Color(0xFFD1D5DB)
val PerformanceGreyBorderDark = Color(0xFF4B5563)
